### ISSUE TITLE
Reruns Not Appearing in Search and Followed

### ISSUE THREAD

**Issue by K0RP53** [FrozenIronSoftware/Twitched#21]
### Description
The official app can locate the channels obviously but both trying to search for the channels or send to roku via twitched Android app fails to play channel. It appears to attempt to play the stream because of the roku menu behavior but fails to even display the load bar suggesting it never makes a connection i guess. 

### Steps to Reproduce
1. Find a stream that is in subscriber only mode. (typically people are still allowed to watch but cannot chat.) example channel that does sub mode: MaryJLeeee
2. Attempt to share to roku. (assuming you are a follower of the channel, it will not be listed in twitched roku menu.) 

...

**Expected behavior:** [You should still be able to see channel in followers and be able to stream it.]

**What actually happened:** [The opposite.]

**Roku Model:** [Roku 4 - 4400x]

**Roku Firmware Version:** [8.0.0 - 4184-17] 

**Twitched Version:** [1.4]

### Additional Information
[NA]

**Comment by rolandoislas** [comment]
The issue seems to be related to re-runs. Unfortunately, Twitch's Helix API does not provide support for re-runs.

**Comment by isaacl** [comment]
You can still watch reruns by just playing a stream that’s listed as offline. Which is a reasonable workaround imo
