### ISSUE TITLE
Remember last watched location when resuming VODs

### ISSUE THREAD

**Issue by artemzakharov** [FrozenIronSoftware/Twitched#35]
The app currently does not remember the location I previously stopped watching at when I resume watching a VOD. This is frustrating because I frequently watch VODs of past streams that are many hours long, and I have to wind forward every time I resume watching after switching to another app or turning off the TV. 

**Describe the solution you'd like**
I would like for the app to save the current location of a VOD when Twitched is closed or minimized, and return to said location immediately when I resume watching said VOD.

**Describe alternatives you've considered**
I can't imagine any alternatives to this feature other than manually skipping forward, which requires memorizing the exact location every time.

**Comment by rolandoislas** [comment]
This has been implemented in the 1.7 beta.
