### ISSUE TITLE
Error code 1005

### ISSUE THREAD

**Issue by talonxavier** [FrozenIronSoftware/Twitched#41]
### Description
No Twitched streams load in Roku over the past 10 days. 

### Steps to Reproduce
1. select Twitched app on Roku
2. All stream icons show a picture of a large question mark and a small question mark 
3. Select any picture to enter specific stream
4. Streamer’s icon shows as 1 question mark
5. Select “Play”
6. The “Retrieving” status bar loads only to about 10% 

...

**Expected behavior:** Streams should load

**Actual behavior:** no streams load

**Roku Model:** 3600X

**Roku Firmware Version:**  9.0.0 build 4084–24

**Twitched Version:** 1.6 build 2910

### Additional Information
[Any other information related to the problem]

**Comment by rolandoislas** [comment]
This appears to be a problem with the Roku's connection to Twitch's (not Twitched's) servers. Ensure other devices on the network can access Twitch.

**Comment by talonxavier** [comment]
I also have a RCA Roku TV which did not have Twitched or Twitched Zero I stalled in it. I just installed Twitched Zero and got the exact same result.

**Comment by rolandoislas** [comment]
Can other devices on the network access Twitch \([twitch.tv](https://www.twitch.tv)\)?

**Comment by talonxavier** [comment]
Do you mean like my computers, iPhones, tablets?  Oh yeah - zero issues whatsoever.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by sporach** [comment]
I've encountered a similar problem, but with a -3 error code. After streaming for a bit, streams load for at most a minute before reloading then saying that the stream is offline (double checking with the twitch website on my desktop shows that the stream is online).

**Comment by talonxavier** [comment]
I determined what the issue was. A few months ago, we installed a product called Circle By Disney on to our network to monitor our child’s internet activity,  remove access based on EACH DEVICE and/or EACH PROFILE. I forgot I had the ROKU TV and the ROKU Dongle assigned to my son temporarily so I could remove his access to social media on those devices post bedtime.

Once I reassigned those devices back to my profile, everything loaded. So even though the app loaded, Circle By Disney must have blocked only certain parts of the app.   Cheers!



Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
