### ISSUE TITLE
Can't install Twicthed on my Roku

### ISSUE THREAD

**Issue by mafiosini** [FrozenIronSoftware/Twitched#46]
**Describe the bug**
When I bought Twitched I couldn't install it. I contacted with Roku support service but the solution that they gave me then didn't help and the only solution was to contact your support service.

**To Reproduce**
1. Go to: channels
2. Select twitched
3. Click on install
4. See error "Couldn't install twitched".

**Expected behavior**
It should be expected to let me install twitched. 

**Roku (please complete the following information):**
 - Roku Firmware: 9.0.0
 - Roku Model: Streaming stick+
 - Twitched Version: Twitched 1.7

**Comment by rolandoislas** [comment]
Unfortunately, we have no control over the install process on the Roku.
