### ISSUE TITLE
Twitched Stuck  on retrieving screen

### ISSUE THREAD

**Issue by Vicnick31** [FrozenIronSoftware/Twitched#51]
**Describe the bug**
Stuck on retrieving screen. Never loads stream

**To Reproduce**
1. Go to 'Home'
2. Select 'Stream'
3. See error

**Expected behavior**
Stays on black screen stating Retrieving and never loads stream

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Roku (please complete the following information):**
 - Roku Firmware: 8.2.0 build 4170-48
 - Roku Model: TCL 40s325
 - Twitched Version: Twitched

**Comment by rdpa** [comment]
Same on
- Roku Firmware: 8.2.0 build 4170-30
- Roku Model: TCL 55R617
- Twitched Version: 1.7 build 3012

**Comment by seanssel** [comment]
Same. Tried system restart, logout, and different local fetching/quality options; all streams stuck retrieving. 

- Roku Firmware: 8.2.0 build 4170-30
- Roku Model: TCL 49S405
- Twitched Version: 1.7 build 3012

**Comment by rolandoislas** [comment]
Are the Roku models provided the same models listed under the `Settings > System > About` page?

**Comment by Vicnick31** [comment]
Yes. It is a Roku TV

**Comment by seanssel** [comment]
The model I provided is referred to as "TCL model" on the about page. It also says "Roku TV: 7104X".

**Comment by 3485743897543** [comment]
I'm having this problem too. Could this be related to this recent rollout by Twitch? https://www.resetera.com/threads/adblocker-no-longer-effective-on-twitch-tv.105808/

**Comment by rolandoislas** [comment]
Unfortunately our TCL Roku TV shipment has been delayed. We are not able to effectively investigate the issue until it arrives.

**Comment by rdpa** [comment]
I've found that if i let it sit on retrieving for ~30 seconds, then hit back on the remote, then hit play again, it seems to work

**Comment by 3485743897543** [comment]
Both the official Twitch channel and Twitched work for me again on my Roku TV 55R615.

**Comment by rolandoislas** [comment]
There is an update that should fix the issue.

Twitched Zero Beta: https://my.roku.com/add/G2PG5Q
Twitched Beta: https://my.roku.com/add/GMMJX9
