### ISSUE TITLE
Sideload Twitched app on non-Roku branded devices

### ISSUE THREAD

**Issue by danmac** [FrozenIronSoftware/Twitched#52]
### Description
I have a non-Roku branded Roku (Telstra TV in Australia) and it has a very limited number of apps available in their channel store. I want to install Twitched (either Zero or I'll pay you for access) but the only way to do it on my device is to use developer mode and sideload it. 

Are you able to provide me with the actual package so I can do this?

**Comment by rolandoislas** [comment]
Unfortunately, we do not provide a side-loadable package. We can look into getting Twitched on the Telstra TVs, however, it would be up to them to allow the application on their hardware.

**Comment by danmac** [comment]
I will ask them but as an unofficial app I doubt it will happen. Thanks
