### ISSUE TITLE
Stuck on 'Loading' for all channels

### ISSUE THREAD

**Issue by amsluis** [FrozenIronSoftware/Twitched#53]
This just started for me this morning, but it's slightly different from the 'retrieving' issue others have had.

Trying to watch any stream or vod brings up the 'Loading' popup, but nothing loads. I've tried ensuring that I was subbed to the channel I tried to load (i.e. an issue with the new in-stream ads), different channels, vods, etc. I've restarted the roku, tried updating, etc. Nothing has worked so far.

I have had no issues up to this point.

Roku 3810X streaming stick+

System: v9.0.0 build 4142-50
Twitched: v1.7 build 3016 (not zero, I have the paid version)

Issue posted to Reddit here: https://old.reddit.com/r/twitched/comments/b6kfb6/stuck_on_loading_for_all_channels/?

**Comment by rolandoislas** [comment]
One of Twitch's API servers is having issues.
